// CRUD PARA REMINDER MODEL
export const READ_REMINDERS = 'READ_REMINDERS';
export const READ_REMINDERS_SUCCESS = 'READ_REMINDERS_SUCCESS';
export const READ_REMINDERS_ERROR = 'READ_REMINDERS_ERROR';

export const CREATE_REMINDER = 'CREATE_REMINDER';
export const CREATE_REMINDER_SUCCESS = 'CREATE_REMINDER_SUCCESS';
export const CREATE_REMINDER_ERROR = 'CREATE_REMINDER_ERROR';

export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS';
export const UPDATE_REMINDER_ERROR = 'UPDATE_REMINDER_ERROR';

export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_ERROR = 'DELETE_REMINDER_ERROR';

// OTHER MODEL